### ISSUE TITLE
QPDFVIEW don't print on printer attached with socket (network printer) in CUPS

### ISSUE THREAD

**Issue by GAnchieri** [bitwiseworks/cups-os2#2]
A years ago, I've acquired a new printer; HP OFFICEJET PRO 8610 that's a network printer with a USB port attachement. Recently a few week ago, I have decided to use it as a network instead of USB and so I installed it as a new Net printer under CUPS. If I print using USB port QPDFVIEW print immediately but if want print using the Net version the CUPS wait with msg: the printer is not responding. 

file:///L:/Programs/ArcTool/Cups-log.zip
![2018-07-net](https://user-images.githubusercontent.com/13507806/42819795-15f1c67c-89c4-11e8-8eb8-09a034ee4a18.jpg)
![2018-07-net-01](https://user-images.githubusercontent.com/13507806/42819815-239c58c8-89c4-11e8-871b-87885864df00.jpg)

**Comment by GAnchieri** [comment]
Add also the log file with debug2.
[error_log1.txt](https://github.com/bitwiseworks/cups-os2/files/2201842/error_log1.txt)

**Comment by SilvanScherrer** [comment]
Strange case. The log clearly says it can't connect to the printer. Means it can't connect to the ip address. Somehow I doubt anything else can print to it through cups. Are you 100% sure other apps print through cups? Or do the print direct?

**Comment by SilvanScherrer** [comment]
Does ping to this ip address work?

**Comment by GAnchieri** [comment]
this is the response to ping cmd:
[L:\]ping 192.168.1.5
PING 192.168.1.5: 56 data bytes
64 bytes from 192.168.1.5: icmp_seq=0. time=0. ms
64 bytes from 192.168.1.5: icmp_seq=1. time=0. ms
64 bytes from 192.168.1.5: icmp_seq=2. time=0. ms
64 bytes from 192.168.1.5: icmp_seq=3. time=0. ms
64 bytes from 192.168.1.5: icmp_seq=4. time=0. ms
64 bytes from 192.168.1.5: icmp_seq=5. time=0. ms
64 bytes from 192.168.1.5: icmp_seq=6. time=0. ms

----192.168.1.5 PING Statistics----
7 packets transmitted, 7 packets received, 0% packet loss
round-trip (ms)  min/avg/max = 0/0/0
I attach a file: 2018-07-router.jpg 
![2018-07-router](https://user-images.githubusercontent.com/13507806/42881425-adb6e2b8-8a86-11e8-863b-8700ce89bf75.jpg)

**Comment by SilvanScherrer** [comment]
can you telnet to the printer? telnet -p9100 192.168.1.5
as as long as the socket.exe from cups can't connect to it it will be hard to find a solution.

**Comment by GAnchieri** [comment]
After a new test, the printer function using sockets. 
I don't know what is succes in the meantime, I have only executed the ping cmd and viewed the setting of router as you can see in preceeding post. for now I close this issue

**Comment by SilvanScherrer** [comment]
for me it looks like something connected and did not disconnect. But good it's solved now
