### ISSUE TITLE
cups-2.2.12-1.oc00.i686.rpm fails to unpack

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/cups-os2#6]
The above package is currently in netlabs-rel. Unfortunately, rpm 4.13.9-19 with cpio 2.12-1 seems unable to properly unpack it for updating/installing. The full error is:

error: unpacking of archive failed on file /@unixroot/var/run/cups/certs: cpio: unlink

md5sum of downloaded package is:

12904b0450c0efe775a2fb09c8bd2df7

pentium4 package fails similarly (certs will not unlink).

**Comment by SilvanScherrer** [comment]
how you you use cpio?
as installing the package works flawless iirc. at least we got no message it's not installable.

**Comment by LewisR** [comment]
rpm uses cpio.

The error occurs whether installing via yum or locally, with rpm (e.g., rpm -Uvh cups-2.2.12-1.oc00.i686.rpm <Enter>).

unrpm seems to work fine extracting the package content.

On the subject system, I just discovered that /var/run/certs is a directory flagged read-only. This is also the case in the rpm. I can't see how this will end well with a read-only directory in the filesystem being replaced by a read-only directory. Is that intentional?

**Comment by LewisR** [comment]
Removing the existing read-only directory allows the update to proceed, however, during cleanup, I get 21 instances of:

read: 0x13f770, 512: Permission denied

The cups daemon was not running during the update.

**Comment by LewisR** [comment]
A yum reinstall of cups seems to work without error following the above.

**Comment by SilvanScherrer** [comment]
I can't reproduce the error with the latest cups rpm. And to be honest I never saw an issue while I upgraded a lot cups.
do only new installs fail?

**Comment by LewisR** [comment]
Interestingly enough, it seems that cups 2.1.3 does not create the certs subdirectory, but 2.2 does, and the directory is created RO. Still, I've tried to reproduce the error here installing fresh and upgrading from several different cups versions, and I can't get the problem to recur.

I can only guess that something in the failing configuration was preventing the certs directory to be overwritten. This must have been a one-off. No change needed.
