### ISSUE TITLE
cupsim.dll from cups-libs-2.2.12-1 fails to load when called by GSOS2.EXE from ghostscript-9.18-7

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/cups-os2#8]
Poor description; sorry.

PMPDF is configurd to load GS from J:\usr (J: is %UNIXROOT%). Attempting to process an incoming stream, the following is captured in POPUPLOG.OS2:

01-12-2021  14:11:58  SYS2070  PID 00a1  TID 0001  Slot 00ce
J:\USR\BIN\GSOS2.EXE
CUPSIM->CUPS.__cups_debug_printf
127 

Rolling cups (and cups-libs, etc.) back to 2.1.3-10 resolves the error.

**Comment by SilvanScherrer** [comment]
the export is in the dll. I'm pretty sure you have a wrong dll somewhere. check your env!!!

**Comment by SilvanScherrer** [comment]
hmm no further comment. so closing it
