### ISSUE TITLE
cupsd.exe startup fails with a SYS2070 

### ISSUE THREAD

**Issue by dspiatkowski** [bitwiseworks/cups-os2#9]
This is a brand new install (1:2.2.13-1.oc00) from netlabs-exp repo.

I let ANPM drive this, all RPMs installed successfully, however attempting to start cupsd.exe produces the following in my popuplog.os2 file:

    09-08-2021  17:30:00  SYS2070  PID 03fb  TID 0001  Slot 0136
    G:\USR\SBIN\CUPSD.EXE
    CUPSD->CUPS.__httpTLSSetOptions
    127

Maybe this is somehow related to this being an EXP repo? I have not tried un-installing and re-installing teh 2.2.12 stable release yet. Wanted to check-in first to see if this was a known issue, haven't found anything looking through the Issues list though.

Thanks!

**Comment by dspiatkowski** [comment]
Further on, I rebooted the box thinking that maybe something to do with TLS needed a "re-set".

That took things a step further, however I am still seeing an error:

09-08-2021  20:48:27  SYS2070  PID 0058  TID 0001  Slot 0094
G:\USR\SBIN\CUPSD.EXE
CUPS->GTLS30._gnutls_fips140_set_mode
127

Currently I have gnutls 3.6.12-1 (pentium4) verison installed here.

**Comment by SilvanScherrer** [comment]
Are you sure you dont have a 2nd gtls30.dll somewhere which is already loaded?

**Comment by dspiatkowski** [comment]
Hmm...excellent pointer, I had searched through the \usr\lib as well as my old (pre-RPM) DLL path locations, but what I did not suspect is that I would find another DLL in the \usr\local\lib location.

[G:\]dir gtls30.dll /s |less

The volume label in drive G is OS2.
The Volume Serial Number is 45B6:75C3.

=== START ===
Directory of G:\usr\lib

 4-04-20  6:20a     1,009,710    124 a---  gtls30.dll
        1 file(s)   1,009,710 bytes used

Directory of G:\usr\local\lib

 1-22-17  2:14a     2,101,262    124 a---  gtls30.dll
        1 file(s)   2,101,262 bytes used
Total files listed:
        2 file(s)     3,110,972 bytes used
                   98,859,499 K bytes free
(END)
=== END ===

Indeed a duplicate DLL.

Further on, I discovered that I also have the following GTLS DLLs in that local\lib location:

 1-22-17  2:14a        90,134    124 a---  gtlsos27.dll
 1-22-17  2:14a       147,472    124 a---  gtlsxx28.dll

I was able to find that gtlsxx28.dll is provided by the gnutls-c++-3.6.12-1.oc00.pentium4 package, so I have that installed now.

However, I do not see a 3.6.12 version of gnutls* providing the gtlsos27.dll, the only RPM package that I found out there is this:

gnutls-3.5.8-1.oc00.i686 : A TLS protocol implementation
Repo        : arcanoae-rel
Matched from:
Other       : gtlsos27.dll

...but that would downlevel the gnutls to 3.5.8, so I will not go down that route.

Either way, I am not sure how these got into that location, but I am testing stuff off of the AOS Testers List, so maybe I did NOT clean up properly after such a test?

Anyways, appreciate the feedback, it was absolutely the right pointer. I will re-boot now and try cupsd.exe again.

thanks!

**Comment by dspiatkowski** [comment]
Good news, I am UP and RUNNING with CUPS here.

My printer PPD requires the deployment of printer filter script...haven't found any relevant information for our port of CUPS yet though...any suggestions where I can find this?

Thanks!

**Comment by SilvanScherrer** [comment]
as the origin issue is fixed i close this issue.
about the filters. all depends on the printer. we have already hundreds of printers working with hplip and gutenprint. but some printer use native filters, which need a port first. and some filters are closed source.
